name: CI workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  test:
    permissions: write-all # for Report LCOV to work

    runs-on: ubuntu-latest

    env:
      PORT: 5000
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_NAME: db_test
      COGNITO_USER_POOL_ID: local_0tm1eyyS # Mocked, can be any value that complies with the amazon-cognito-identity-js library
      COGNITO_CLIENT_ID: dy84cymh67njie4bdru9g3rk2 # Mocked, can be any value that complies with the amazon-cognito-identity-js library
      COGNITO_ISSUER: http://localhost:9229/local_0tm1eyyS # Mocked, can be any value that complies with the amazon-cognito-identity-js library
      COGNITO_ENDPOINT: http://localhost:9229 # Mocked, can be any value that complies with the amazon-cognito-identity-js library
      BASE_APP_URL : http://localhost:9229/api/v1 # Mocked, can be any value but it must contain /api/v1

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Build and test with coverage
        run: npm run test:cov

      - name: Report LCOV
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-files: ./coverage/lcov.info

      - name: Store coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

  scan:
    needs: test

    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Retrieve coverage
        uses: actions/download-artifact@v3.0.0
        with:
          name: coverage
          path: coverage

      - name: Scan with Sonarqube
        uses: sonarsource/sonarqube-scan-action@master

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
